const BondApiErrors = {
  vi: {
    "BOND-1004": "Không xác định được lãi suất sản phẩm",
    "BOND-1024": "Trùng lãi suất sản phẩm",
    "BOND-1020": "Lãi suất sản phẩm không hợp lệ",
    "BOND-1011": "Tỷ lệ lãi suất sản phẩm không hợp lệ",
    "BOND-1012": "Kỳ hạn lãi suất sản phẩm không hợp lệ",
    "BOND-1013": "Định dạng tỷ lệ lãi suất không hợp lệ",
    "BOND-1028": "Kỳ hạn lãi suất đã trùng",

    "BOND-1017": "Kích thước trang dữ liệu không hợp lệ",
    "BOND-1002": "Không tìm thấy mã sản phẩm",
    "BOND-1027": "Loại sản phẩm đã tồn tại!",
    "BOND-1008": "Hạn mức sản phẩm không hợp lệ",
    "BOND-1009": "Ưu đãi sản phẩm không hợp lệ",
    "BOND-1113": "Không thể thay đổi mã sản phẩm",
    "BOND-1015": "Mã trái phiếu không hợp lệ",
    "BOND-1049": "Lợi tức không hợp lệ",

    "BOND-1001": "Không tìm thấy giao dịch",
    "BOND-1047": "Ngày giao dịch không hợp lệ",
    "BOND-1038": "Tên tài khoản thụ hưởng không hợp lệ",
    "BOND-1040": "Mã Ngân hàng không hợp lệ",
    "BOND-1042": "Mã Chi nhánh không hợp lệ",
    "BOND-1043": "Tên Chi nhánh không hợp lệ",
    "BOND-1050": "Ngày giao dịch phải trước ngày thanh toán",
    "BOND-1057": "Ngày thanh toán phải trước ngày trả lại",
    "BOND-1026": "Ưu đãi giao dịch không hợp lệ",

    "BOND-1019": "Mã lỗi đã trùng",
    "BOND-1052": "Không tìm thấy thông tin người bán",
    "BOND-1085":
      "Hạn mức còn lại của sản phẩm không đủ để thực hiện giao dịch!",
    "TBOND-003": "Lệnh đặt không thành công do Hết giờ giao dịch",
    "BOND-1115": "Mã nhân viên chăm sóc không tồn tại. Vui lòng thử lại.",
    "BOND-1105": "Khối lượng đặt vượt quá khối lượng có trong tài khoản!",

    "BOND-2001": "Lỗi server. Quý khách vui lòng tải lại trang để khắc phục.",
    "BOND-2002": "Phương thức thanh toán không hợp lệ",
    "BOND-1003": "Mã sản phẩm không hợp lệ",
    "BOND-1005": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409.",
    "BOND-1121": "Khối lượng giao dịch không hợp lệ. Vui lòng thử lại.",
    "BOND-1066": "Ngày giao dịch không hợp lệ",
    "BOND-1082": "Trạng thái giao dịch không hợp lệ",
    "BOND-1078": "Số lượng vượt quá số lượng còn lại của sản phẩm",
    "BOND-1084":
      "Khối lượng giao dịch không thỏa mãn điều kiện về khối lượng sở hữu tối thiểu. Vui lòng kiểm tra lại hoặc liên hệ NVCS hoặc 1900545409.",
    "BOND-1037": "Ngày trả lại trái phiếu phải trước ngày đáo hạn",
    "BOND-1148": "Không tìm thấy mã ưu đãi",

    "CONGEN-001": "Thông tin đầu vào chưa chính xác. Vui lòng kiểm tra lại",
    "CONGEN-002": "Thông tin khách hàng không tồn tại.",
    "CONGEN-003":
      "Truy vấn thông tin khách hàng thất bại. Vui lòng liên hệ nhân viên chăm sóc để được hỗ trợ.",
    "CONGEN-004": "Không tìm thấy thông tin",
    "CONGEN-005": "Truy vấn thông tin trái phiếu không thành công",
    "CONGEN-006": "Hợp đồng trái phiếu không tồn tại",
    "CONGEN-007": "Thông tin yêu cầu không hợp lệ",
    "CONGEN-008": "Thông tin yêu cầu không hợp lệ",
    "CONGEN-009": "Thông tin yêu cầu không hợp lệ",
    "CONGEN-010": "Lỗi hệ thống",
    "CONGEN-011": "Lỗi hệ thống",
    "CONGEN-012": "Thông tin không hợp lệ",
    "CONGEN-013": "Lỗi hệ thống",
    "CONGEN-014": "Lỗi hệ thống",
    "CONGEN-015": "Thông tin yêu cầu không hợp lệ",
    "CONGEN-016": "Hợp đồng đã được xác thực. Vui lòng không xác thực lại.",
    "CONGEN-017": "Thông tin yêu cầu không hợp lệ",
    "CONGEN-018": "Thông tin yêu cầu không hợp lệ",
    "CONGEN-019": "Trạng thái tài khoản không hợp lệ",
    "CONGEN-020": "Loại hình tài khoản không hợp lệ",
    "CONGEN-021": "Lỗi hệ thống",
    "CONGEN-022": "Lỗi hệ thống",
    "CONGEN-023": "Lệnh đặt không thành công do hết giờ giao dịch",
    "CONGEN-024": "Ngày thanh toán không hợp lệ",

    "BOND-1044": "Phương thức thanh toán không hợp lệ",
    "BOND-1046": "Phương thức thanh toán gốc/lãi không hợp lệ",
    "BOND-1051": "Biên lãi suất tham chiếu không hợp lệ",
    "BOND-1053": "Thông tin khách hàng không hợp lệ",
    "BOND-1054": "Tên người bán không hợp lệ",
    "BOND-1055": "Mã giới thiệu không hợp lệ",
    "BOND-1056": "Không được phép đổi trạng thái giao dịch.",
    "BOND-1058": "Thuế phải lớn hơn hoặc bằng 0",
    "BOND-1059": "Phí mua phải lớn hơn hoặc bằng 0",
    "BOND-1060": "Phí bán phải lớn hơn hoặc bằng 0",
    "BOND-1062": "Tài khoản ngân hàng của người bán bị trùng",
    "BOND-1063": "Tên ngân hàng của người bán không hợp lệ",
    "BOND-1064": "Lãi suất và lợi tức phải lớn hơn 0",
    "BOND-1067": "Ngày giao dịch không hợp lệ",
    "BOND-1068": "Ngày đáo hạn không hợp lệ",
    "BOND-1069": "Không tìm thấy giao dịch",
    "BOND-1070": "Ưu đãi không hợp lệ",
    "BOND-1071": "Không tìm thấy ngày trả lãi coupon",
    "BOND-1072": "Ngày trả lãi coupon không hợp lệ",
    "BOND-1073": "Ngày trả lãi coupon không hợp lệ",
    "BOND-1074": "Lãi suất tham chiếu không hợp lệ",
    "BOND-1076": "Ngày hiệu lực không hợp lệ",
    "BOND-1077": "Dòng tiền không hợp lệ",
    "BOND-1079": "Khối lượng giao dịch không hợp lệ",
    "BOND-1080": "Loại giá phải là cố định hoặc thả nổi",
    "BOND-1081": "Ngày giao dịch phải sau ngày hiệu lực",
    "BOND-1083": "Giao dịch không hợp lệ: Giao dịch đã tồn tại",
    "BOND-1086": "Không tìm thấy thông tin thuế thu nhập cá nhân",
    "BOND-1089": "Không tìm thấy phí đã thanh toán",
    "BOND-1090": "Trạng thái giao dịch không hợp lệ",
    "BOND-1092": "Loại thanh toán không hợp lệ",
    "BOND-1093": "Biên lãi suất không hợp lệ",
    "BOND-1094": "Lãi suất không hợp lệ",
    "BOND-1095": "Tỷ lệ coupon không hợp lệ",
    "BOND-1096": "Tỷ lệ Buy Back không hợp lệ",
    "BOND-1098": "Không tìm thấy mã trái phiếu đang giao dịch",
    "BOND-1099": "Thanh toán không thành công",
    "BOND-1100": "Không tìm thấy khoản thanh toán",
    "BOND-1101": "Giá không hợp lệ",
    "BOND-1102": "Trạng thái giao dịch không hợp lệ",
    "BOND-1103": "Loại giao dịch không hợp lệ",
    "BOND-1104": "Phí không hợp lệ",
    "BOND-1107": "Giao dịch thanh toán đã tồn tại",
    "BOND-1108": "Tài sản đã tồn tại",
    "BOND-1109": "Không tìm thấy tài sản",
    "BOND-1110": "Chênh lệnh giá mua không hợp lệ",
    "BOND-1111": "Tài khoản thụ hưởng không hợp lệ",
    "BOND-1112": "Tên tài khoản thụ hưởng không hợp lệ",
    "BOND-1114": "Chênh lệch giá bán không hợp lệ",
    "BOND-1116": "Không tìm thấy giá tùy chỉnh riêng",
    "BOND-1117": "Mức giá tùy chỉnh riêng này đã tồn tại",
    "BOND-1118": "Dữ liệu không đúng định dạng",
    "BOND-1119": "Khối lượng tối đa phải lớn hơn hoặc bằng 0",
    "BOND-1120": "Khối lượng tối thiểu phải lớn hơn hoặc bằng 0",
    "BOND-1122": "Ngày không hợp lệ",
    "BOND-1123": "Khách hàng chưa hoàn thiện hợp đồng mở tài khoản",
    "BOND-1124": "Giá trị tài sản ròng không hợp lệ",
    "BOND-1125": "Giá trị ưu đãi không hợp lệ",
    "BOND-1126": "Không tìm thấy ưu đãi",
    "BOND-1127": "Ưu đãi theo NAV này đã tồn tại",
    "BOND-1128": "Trích lục sổ đăng ký NSHTP/GCNSHTP không hợp lệ",
    "BOND_1129": "Lãi suất thanh toán trước hạn không hợp lệ",
    "BOND_1130": "Số ngày nắm giữ tối thiểu không hợp lệ",
    "BOND_1131": "Lỗi hệ thống",
    "BOND_1132": "Lỗi hệ thống",
    "BOND_1133": "Yêu cầu ngày trả lãi coupon không hợp lệ",
    "BOND-1134": "Không tìm thấy nội dung đã tạo",
    "BOND-1135": "Nội dung vừa tạo đã tồn tại!",
    "BOND-1136": "Nội dung vừa kiểm tra đã tồn tại!",
    "BOND-1137": "Bảng lãi suất theo kỳ hạn đã tồn tại!",
    "BOND-1138": "Khối lượng được bán và khối lượng trái phiếu không hợp lệ",
    "BOND-1139": "Phương thức tính dòng tiền phải là 1 hoặc 2",
    "BOND-1140": "Tần suất trả lãi không hợp lệ",
    "BOND-1141": "Số dư tối thiểu không hợp lệ",
    "BOND-1142": "Lỗi khai báo Promotion code: để trống, trùng Promotion Code",
    "BOND-1143": "Lỗi khai báo Promotion code: ngày hiệu lực không hợp lệ",
    "BOND-1144": "Lỗi khai báo Promotion code: ngày hết hạn không hợp lệ",
    "BOND-1145": "Lỗi khai báo Promotion code: Code limit không hợp lệ",
    "BOND-1146": "Lỗi khai báo Promotion code: Customer ID limit không hợp lệ",
    "BOND-1147": "Lỗi khai báo Promotion code: Careby limit không hợp lệ",
    "BOND-1149":
      "Lỗi xóa Promotion code: Không được xóa khi Careby Code đã sử dụng Code",
    "BOND-1150":
      "Lỗi edit Promotion Code: Không truyền thông tin promotion code id",
    "BOND-1151":
      "Lỗi xóa Promotion customer id: Không được xóa khi customer id đã sử dụng Code",
    "BOND-1153": "Không thể áp dụng mã ưu đãi này cho ngày giao dịch đã chọn",
    "BOND-1154": "Mã ưu đãi đã hết lượt sử dụng",
    "BOND-1030": "Mã giới thiệu không đúng",

    "BOND-1155": "KL nắm giữ tối đa không hợp lệ",
    "BOND-1156": "Ngày hiệu lực không hợp lệ",
    "BOND-1157": "Kênh tạo giao dịch không hợp lệ",
    "BOND-1158": "Giao dịch hoán đổi không hợp lệ",
    "BOND-1159": "Ngày thanh toán không hợp lệ",
    "BOND-1160": "Ngày thanh toán không hợp lệ",
    "BOND-1161": "Giao dịch đã có lệnh thỏa thuận",
    "BOND-1162": "Giao dịch không hợp lệ",
    "BOND-1163": "Giao dịch không hợp lệ",
    "BOND-1164": "Giao dịch leg2 không hợp lệ",
    "BOND-1165": "Giao dịch leg2 không hợp lệ",
    "BOND-1166": "Số ngày không hợp lệ",
    "BOND-1167": "Ngày tất toán không hợp lệ. Vui lòng chọn ngày khác.",
    "BOND-1168": "Giá mua lại không hợp lệ",
    "BOND-1169": "Số ngày thông báo không hợp lệ",
    "BOND-1170":
      "Khối lượng không thỏa mãn điều kiện về khối lượng sở hữu tối đa",
    "BOND-1171": "Khối lượng chưa đạt mức tối thiểu để hưởng mã ưu đãi",
    "BOND-1172": "Khối lượng lớn hơn mức tối đa được hưởng mã ưu đãi",
    "BOND-1173": "Sản phẩm không hợp lệ",
    "BOND-1174": "Ngày phát hành không hợp lệ",
    "BOND-1175": "Loại hình phát hành không hợp lệ",
    "BOND-1176": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409",
    "BOND-1177": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409",
    "BOND-1178": "Sản phẩm dành cho Nhà đầu tư Chuyên nghiệp",
    "BOND-1180": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409",
    "BOND-1181": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409",
    "BOND-1182": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409",
    "BOND-1183": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409",
    "BOND-1184": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409",
    "BOND-1185": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409",
    "BOND-1186": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409",
    "BOND-1187": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409",
    "BOND-1188": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409",
    "BOND-1189": "Lỗi hệ thống.Vui lòng liên hệ NVCS hoặc 1900545409",
    "BOND-1190": "Không đủ sức mua. Vui lòng thử lại.",

    "BOND-1191": "Lỗi truyền sai rounding method Buyback",
    "BOND-1192": "Lỗi truyền thiếu param termRateId khi get leg2 trade date",
    "BOND-1193": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409.",
    "BOND-1194": "Lỗi không tìm thấy property name",
    "BOND-1195": "Lỗi property value không hợp lệ",
    "BOND-1196": "Chi tiết mã ưu đãi đã tồn tại",
    "BOND-1197": "Ngày đặt lệnh phải nhỏ hơn hoặc là ngày hiện tại",
    "BOND-1198": "Khách hàng phải là Nhà đầu tư chuyên nghiệp",
    "BOND-1199": "Ngày giao dịch của lệnh tương lai không hợp lệ",
    "BOND-1200": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409.",
    "BOND-1201": "Thiếu ngày thanh toán. Vui lòng thử lại.",
    "BOND-1202": "Product type is not supported",
    "BOND-1203": "Bảng lãi suất không hợp lệ",
    "BOND-1204": "Kỳ hạn được chọn vượt quá kỳ hạn tối đa của trái phiếu",
    "BOND-1205": "",
    "BOND-1206": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409.",
    "BOND-1207": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409.",
    "BOND-1208":
      "Ngày đặt lệnh và ngày thanh toán phải dưới định dạng 'yyyy-MM-dd'. Vui lòng thử lại.",
    "BOND-1209": "Giới hạn ngày đặt lệnh tương lai: Tối đa 30 ngày",
    "BOND-1210":
      "Ngày tất toán phải trước hoặc tại ngày chốt danh sách trả gốc trái phiếu. Vui lòng kiểm tra lại hoặc liên hệ NVCS hoặc 1900545409.",
    "BOND-1211":
      "Ngày tất toán phải sau ngày mua trái phiếu. Vui lòng thử lại.",
    "BOND-1212":
      "Ngày tất toán vượt quá kỳ hạn đầu tư tối đa của trái phiếu. Vui lòng kiểm tra lại hoặc liên hệ NVCS hoặc 1900545409.",
    "BOND-1217":
      "Giá trị giao dịch vượt hạn mức đặt lệnh. Vui lòng kiểm tra lại hoặc liên hệ NVCS hoặc 1900545409.",
    "BOND-1218":
      "Giá trị giao dịch vượt hạn mức của tài khoản. Vui lòng kiểm tra lại hoặc liên hệ NVCS hoặc 1900545409.",
    "BOND-1219":
      "Giá trị giao dịch vượt hạn mức của Khách hàng. Vui lòng kiểm tra lại hoặc liên hệ NVCS hoặc 1900545409.",
    "BOND-1220":"Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409.",
    "BOND-1221":"Số lượng có thể bán không hợp lệ. Vui lòng kiểm tra lại hoặc liên hệ NVCS hoặc 1900545409.",
    "BOND-1222":"Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409.",
    "BOND-1223":"Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409.",
    "BOND-1224": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409.",
    "BOND-1225":"Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409.",
    "BOND-1226":"Số lượng có thể bán không hợp lệ. Vui lòng kiểm tra lại hoặc liên hệ NVCS hoặc 1900545409.",
    "BOND-1227":"Số lượng có thể bán không hợp lệ. Vui lòng kiểm tra lại hoặc liên hệ NVCS hoặc 1900545409.",
    "BOND-1238":"Đặt lệnh không thành công. Trái phiếu đang trong thời gian hạn chế chuyển nhượng.",

    "BPM-200":
      "Giao dịch cần xác nhận trước 15h. Vui lòng thực hiện lại giao dịch khác.",
    "BPM-204": "Yêu cầu không tồn tại hoặc đã được xử lý.",
    "BPM-205": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409.",

    "DPM-28": "Lỗi hệ thống",
    "DPM-19": "Có lỗi trong quá trình tạo văn bản xác nhận",
    "DPM-2802": "Lỗi không đủ số dư khả dụng",
    "DPM-2803": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409.",
    "DPM-2804": "Lỗi không tìm thấy thông tin trong quá trình xử lý",
    "DPM-2805": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409.",
    "DPM-2808": "Có lỗi trong quá trình tạo deal",
    "DPM-2809": "Có lỗi trong quá trình tạo hợp đồng",
  },

  en: {
    "BOND-1004": "The table rate is not found!",
    "BOND-1024": "The table rate name is duplicated",
    "BOND-1020": "The table rate name is invalid",
    "BOND-1011": "The table rate is invalid",
    "BOND-1012": "The table rate term is invalid",
    "BOND-1013": "The table rate term unit is invalid",
    "BOND-1028": "The table rate term is duplicated",

    "BOND-1017": "The param page size is invalid",
    "BOND-1002": "The product code is invalid",
    "BOND-1027": "The product has already existed",
    "BOND-1008": "The product limit is invalid",
    "BOND-1009": "The product promotion is invalid",
    "BOND-1113": "The product ID modification is not allowed",
    "BOND-1015": "The bond code is invalid",
    "BOND-1049": "The product yield is invalid",

    "BOND-1001": "The deal is not found!",
    "BOND-1047": "The trade date is invalid",
    "BOND-1038": "The beneficiary account is invalid",
    "BOND-1040": "The bank code is invalid",
    "BOND-1042": "The brach code is invalid",
    "BOND-1043": "The brach name is invalid",
    "BOND-1050": "The trade date must be before the value date",
    "BOND-1057": "The value date must be before the leg 2 trade date",
    "BOND-1026": "The deal promotion is invalid",

    "BOND-1019": "The error ID is duplicated",
    "BOND-1052": "The market maker is not found",
    "BOND-1085": "The remain limit for product is invalid",
    "TBOND-003":
      "Bond transaction is created unsuccessfully after trading time",
    "BOND-1115": "Careby is not found. Please try again.",
    "BOND-1105":
      "You do not have enough bonds quantity of this symbol in your account!",

    "BOND-2001": "Internal Server Error. Please reload the client.",
    "BOND-2002": "Invalid Payment transaction",
    "BOND-1003": "Invalid product ID",
    "BOND-1005": "Lỗi hệ thống. Vui lòng liên hệ NVCS hoặc 1900545409.",
    "BOND-1121": "Invalid quantity. Please try again.",
    "BOND-1066": "The trading date is invalid",
    "BOND-1082": "Trạng thái giao dịch không hợp lệ",
    "BOND-1078": "Số lượng vượt quá số lượng còn lại của sản phẩm",
    "BOND-1084":
      "Deal quantity does not meet min balance requirement. Please double check or contact your careby or 1900545409 for further detail.",
    "BOND-1037": "Leg2 date is greater than Bond's confirm date",
    "BOND-1148": "Promotion code not found",

    "CONGEN-001": "Input information is not valid. Please validate again.",
    "CONGEN-002": "Customer's information is absent",
    "CONGEN-003":
      "Query to customer information has failed. Please contact with customer service.",
    "CONGEN-004": "Entity is not found",
    "CONGEN-005": "Query to bond's information has failed",
    "CONGEN-006": "Bond contract is absent",
    "CONGEN-007": "Request information is invalid",
    "CONGEN-008": "Request information is invalid",
    "CONGEN-009": "Request information is invalid",
    "CONGEN-010": "System error",
    "CONGEN-011": "System error",
    "CONGEN-012": "Request information is invalid",
    "CONGEN-013": "System error",
    "CONGEN-014": "System error",
    "CONGEN-015": "Request information is invalid",
    "CONGEN-016": "Your contract is confirmed. Please do not confirm again.",
    "CONGEN-017": "Request information is invalid",
    "CONGEN-018": "Request information is invalid",
    "CONGEN-019": "Request information is invalid",
    "CONGEN-020": "Request information is invalid",
    "CONGEN-021": "System error",
    "CONGEN-022": "System error",
    "CONGEN-023":
      "Bond transaction is created unsuccessfully after trading time",
    "CONGEN-024": "The value date is invalid",

    "BOND-1044": "Invalid Payment Method",
    "BOND-1046": "Invalid Bond Payment",
    "BOND-1051": "Invalid Margin Reference Interest",
    "BOND-1053": "Invalid Customer",
    "BOND-1054": "Invalid Market Maker",
    "BOND-1055": "Invalid Reference Code",
    "BOND-1056": "Changing deal status is not allowed.",
    "BOND-1058": "Tax must be equal to or greater than 0",
    "BOND-1059": "Buy Fee must be equal to or greater than 0",
    "BOND-1060": "Sell Fee must be equal to or greater than 0",
    "BOND-1062": "Duplicate Market Maker's Account Bank",
    "BOND-1063": "Invalid Market Maker's Bank Name",
    "BOND-1064": "Rate and Yield must be positive value",
    "BOND-1067": "Invalid Value Date",
    "BOND-1068": "Invalid Maturity Date",
    "BOND-1069": "Transaction Not Found",
    "BOND-1070": "Invalid Product Promotion",
    "BOND-1071": "Schedule Coupon Not Found",
    "BOND-1072": "Invalid Schedule Coupon",
    "BOND-1073": "Invalid Schedule Coupon",
    "BOND-1074": "Invalid Bond Reference Interest Rate",
    "BOND-1076": "Invalid Effective Date",
    "BOND-1077": "Invalid Cash Flow",
    "BOND-1079": "Invalid Transaction Quantity",
    "BOND-1080": "Price Type must be Fix or Float",
    "BOND-1081": "Trade Date must be after Value Date",
    "BOND-1083": "Invalid Leg2 Transaction: Transaction Already Exists",
    "BOND-1086": "Personal Income Tax Not Found",
    "BOND-1089": "Paid Fee Not Found",
    "BOND-1090": "Invalid Deal Status",
    "BOND-1092": "Invalid Payment Type",
    "BOND-1093": "Invalid Margin Rate",
    "BOND-1094": "Invalid Rate",
    "BOND-1095": "Invalid Coupon Rate",
    "BOND-1096": "Invalid Buy Back Rate",
    "BOND-1098": "Trading Bonds Not Found",
    "BOND-1099": "Payment Error",
    "BOND-1100": "Payment Not Found",
    "BOND-1101": "Invalid Price",
    "BOND-1102": "Invalid Transaction Status",
    "BOND-1103": "Invalid Transaction Side",
    "BOND-1104": "Invalid Product Fee",
    "BOND-1107": "Payment Transaction Already Exists",
    "BOND-1108": "Asset already exists",
    "BOND-1109": "Asset Not Found",
    "BOND-1110": "Invalid Product Spread Buy",
    "BOND-1111": "Invalid Benefit Account",
    "BOND-1112": "Invalid Benefit Account Name",
    "BOND-1114": "Invalid Product Spread Sell",
    "BOND-1116": "Custom Price Not Found",
    "BOND-1117": "The same custom price already exists",
    "BOND-1118": "Incorrect data type",
    "BOND-1119": "Max quantity must be equal to or greater than 0",
    "BOND-1120": "Min quantity must be equal to or greater than 0",
    "BOND-1122": "Invalid Input Date",
    "BOND-1123": "Customer has not completed the account opening contract",
    "BOND-1124": "Invalid NAV",
    "BOND-1125": "Invalid promotion value",
    "BOND-1126": "Promotion Not Found",
    "BOND-1127": "NAV promotion already exists",
    "BOND-1128": "Invalid bond certificate",
    "BOND_1129": "Invalid demand rate",
    "BOND_1130": "Invalid deal min holding period",
    "BOND_1131": "System Error",
    "BOND_1132": "System Error",
    "BOND_1133": "Invalid schedule coupon request",
    "BOND-1134": "Made Entity Not Found",
    "BOND-1135": "Entity made already exists!",
    "BOND-1136": "Entity checked already exists!",
    "BOND-1137": "Table rate already exists!",
    "BOND-1138": "Invalid bond quantity and sellable quantity",
    "BOND-1139": "Cashflow type must be 1 or 2",
    "BOND-1140": "Invalid bond paid int period year",
    "BOND-1141": "Invalid min balance",
    "BOND-1142": "Promotion code error: empty field, duplicate code",
    "BOND-1143": "Promotion code error: invalid effective date",
    "BOND-1144": "Promotion code error: invalid expiry date",
    "BOND-1145": "Promotion code error: invalid code limit",
    "BOND-1146": "Promotion code error: invalid Customer ID limit",
    "BOND-1147": "Promotion code error: invalid careby limit",
    "BOND-1149": "Cannot delete promotion code: invalid careby code",
    "BOND-1150": "Cannot edit promotion code: invalid promotion code ID",
    "BOND-1151": "Cannot delete customer ID with promotion code used",
    "BOND-1153": "The promotion code is invalid for this value date",
    "BOND-1154": `The promotion code's usage limit has been reached`,
    "BOND-1030": "Invalid refer code",

    "BOND-1155": "Invalid bond holder limit",
    "BOND-1156": "Invalid value date",
    "BOND-1157": "Invalid deal channel",
    "BOND-1158": "Invalid coupon free deal",
    "BOND-1159": "Invalid settled date",
    "BOND-1160": "Invalid settled date",
    "BOND-1161": "Deal has cross order",
    "BOND-1162": "Invalid deal",
    "BOND-1163": "Invalid deal",
    "BOND-1164": "Invalid leg2 transaction",
    "BOND-1165": "Invalid leg2 transaction",
    "BOND-1166": "Invalid number of days",
    "BOND-1167": "Invalid Leg2 settled date. Please choose different date.",
    "BOND-1168": "Invalid buy back price",
    "BOND-1169": "Invalid issuer notice days",
    "BOND-1170": "Deal quantity does not meet max balance requirement",
    "BOND-1171":
      "Quantity does not reach the minimum volume to use promotion code",
    "BOND-1172": "Quantity is over the maximum volume to use promotion code",
    "BOND-1173": "Invalid product",
    "BOND-1174": "Invalid bond issue date",
    "BOND-1175": "Invalid bond release type",
    "BOND-1176": "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1177": "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1178": "Product for professional investor.",
    "BOND-1180": "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1181": "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1182": "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1183": "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1184": "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1185": "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1186": "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1187": "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1188": "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1189": "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1190": "Not enough purchasing power. Please try again.",

    "BOND-1191": "Invalid rounding method",
    "BOND-1192": "termRateId is required",
    "BOND-1193":
      "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1194": "System property is not found",
    "BOND-1195": "System property value it not valid",
    "BOND-1196": "Promotion code detail already existed",
    "BOND-1197": "Trade Date must <= Current Date",
    "BOND-1198": "Customer must be Professional Investor",
    "BOND-1199": "Value date of early order is invalid",
    "BOND-1200":
      "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1201": "Trans Settled Date is required. Please try again.",
    "BOND-1202": "Không hỗ trợ sản phẩm này",
    "BOND-1203": "Table rate invali",
    "BOND-1204": "Term rate is greater than maximum term of product",
    "BOND-1205": "",
    "BOND-1206":
      "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1207":
      "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1208":
      'fromDate and toDate is mandatory and formatted as "yyyy-MM-dd". Please try again.',
    "BOND-1209":
      "Invalid date range: fromDate must less than toDate and maximum date range is 30 days",
    "BOND-1210":
      "Leg2 Settled Date must <= Principal's confirm date. Please double check or contact your careby or 1900545409 for further detail.",
    "BOND-1211":
      "Leg2 Settled Date must > Leg1's settled date. Please try again.",
    "BOND-1212":
      "Leg2 Settled Date is beyond maximum investing term. Please double check or contact your careby or 1900545409 for further detail.",
      "BOND-1217":
      "Volume exceeds transaction limit. Please double check or contact your careby or 1900545409 for further detail.",
    "BOND-1218":
      "Volume exceeds account transaction limit. Please double check or contact your careby or 1900545409 for further detail.",
      "BOND-1219":
      "Volume exceeds customer limit. Please double check or contact your careby or 1900545409 for further detail.",
    "BOND-1220":"System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1221":"Invalid sellable quantity. Please double check or contact your careby or 1900545409 for further detail.",
    "BOND-1222":"System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1223":"System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1224": "System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1225":"System error. Please contact your careby or 1900545409 for further detail.",
    "BOND-1226":"Invalid sellable quantity. Please double check or contact your careby or 1900545409 for further detail.",
    "BOND-1227": "Invalid sellable quantity. Please double check or contact your careby or 1900545409 for further detail.",
    "BOND-1238":"Orders are not allowed. Product is currently in restricted period",
    
    "BPM-200": "Transaction needs to be confirmed before 15:00. Please try again later.",
    "BPM-204": "The request doesn't exist or has been processed.",
    "BPM-205": "System error. Please contact your careby or 1900545409 for further detail.",

    "DPM-28": "System error",
    "DPM-19": "There was an error while creating the confirmation document",
    "DPM-2802": "The account balance is not sufficient",
    "DPM-2803":
      "System error. Please contact your careby or 1900545409 for further detail.",
    "DPM-2804": "No information found during processing",
    "DPM-2805":
      "System error. Please contact your careby or 1900545409 for further detail.",
      "DPM-2808": "There was an error while creating the deal",
      "DPM-2809": "There was an error while creating the contract",
  },
};

export default BondApiErrors;
