export const LOAD_ORDERBOOK = 'LOAD_ORDERBOOK';
export const LOAD_ORDERBOOK_SUCCESS = 'LOAD_ORDERBOOK_SUCCESS';
export const LOAD_TRANSACTION_LIST = 'LOAD_TRANSACTION_LIST';
export const LOAD_TRANSACTION_LIST_SUCCESS = 'LOAD_TRANSACTION_LIST_SUCCESS';
export const LOAD_PORTFOLIO = 'LOAD_PORTFOLIO';
export const LOAD_PORTFOLIO_SUCCESS = 'LOAD_PORTFOLIO_SUCCESS';

export const GET_TAX = 'GET_TAX';
export const GET_TAX_SUCCESS = 'GET_TAX_SUCCESS';
export const GET_TAX_FAILED = 'GET_TAX_FAILED';

export const GET_BOND_ALL = 'GET_BOND_ALL';
export const GET_BOND_ALL_SUCCESS = 'GET_BOND_ALL_SUCCESS';
export const GET_BOND_ALL_FAILED = 'GET_BOND_ALL_FAILED';

export const GET_BOND_PRODUCTS = 'GET_BOND_PRODUCTS';
export const GET_BOND_PRODUCTS_SUCCESS = 'GET_BOND_PRODUCTS_SUCCESS';
export const GET_BOND_PRODUCTS_FAILED = 'GET_BOND_PRODUCTS_FAILED';

export const GET_BOND_RATES = 'GET_BOND_RATES';
export const GET_BOND_RATES_SUCCESS = 'GET_BOND_RATES_SUCCESS';
export const GET_BOND_RATES_FAILED = 'GET_BOND_RATES_FAILED';

export const CREATE_DEAL = 'CREATE_DEAL';
export const CREATE_DEAL_SUCCESS = 'CREATE_DEAL_SUCCESS';
export const CREATE_DEAL_FAILED = 'CREATE_DEAL_FAILED';

export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_FAILED = 'UPDATE_TRANSACTION_FAILED';

export const LOAD_CUSTOMER_INFO = 'LOAD_CUSTOMER_INFO';
export const LOAD_CUSTOMER_INFO_SUCCESS = 'LOAD_CUSTOMER_INFO_SUCCESS';
export const LOAD_CUSTOMER_SERVICES = 'LOAD_CUSTOMER_SERVICES';
export const LOAD_CUSTOMER_SERVICES_SUCCESS = 'LOAD_CUSTOMER_SERVICES_SUCCESS';
export const LOAD_ACCOUNT_INFO = 'LOAD_ACCOUNT_INFO';
export const LOAD_ACCOUNT_INFO_SUCCESS = 'LOAD_ACCOUNT_INFO_SUCCESS';
export const LOAD_BUY_ACCOUNT_INFO = 'LOAD_BUY_ACCOUNT_INFO';
export const LOAD_BUY_ACCOUNT_INFO_SUCCESS = 'LOAD_BUY_ACCOUNT_INFO_SUCCESS';
export const CLEAR_BUY_ACCOUNT_INFO = 'CLEAR_BUY_ACCOUNT_INFO';
export const LOAD_ALL_ACCOUNTS = 'LOAD_ALL_ACCOUNTS';
export const LOAD_ALL_ACCOUNTS_SUCCESS = 'LOAD_ALL_ACCOUNTS_SUCCESS';

export const OPEN_POPUP = 'OPEN_POPUP';
export const CLOSE_POPUP = 'CLOSE_POPUP';

export const LOAD_SCHEDULE_RESTRICHTED = 'LOAD_SCHEDULE_RESTRICHTED';
export const LOAD_SCHEDULE_RESTRICHTED_SUCCESS = 'LOAD_SCHEDULE_RESTRICHTED_SUCCESS';
export const LOAD_OWNER_ACCOUNT = "LOAD_OWNER_ACCOUNT";
export const LOAD_OWNER_ACCOUNT_SUCCESS = "LOAD_OWNER_ACCOUNT_SUCCESS";