const BondLabelMap = {
  vi: {
    poLabelDbond: "Danh mục DBond",
    poLabelCustodyDbond: "Danh mục DBond chưa hoàn thành ký gửi",
    poLabelVbond: "Danh mục VBond",
    poLabelCustodyVbond: "Danh mục VBond chưa hoàn thành ký gửi",
    ListedBond: "Trái phiếu niêm yết",
    OtherBond: "Trái phiếu khác",
    GovernmentBond: "Trái phiếu Chính Phủ",
    ConvertibleBond: "Trái phiếu chuyển đổi",
    otherBond: "Trái phiếu khác",
    interestBondCoupon: "Lãi suất coupon trái phiếu",
    averageBuyPrice: "Giá mua bình quân",
    accountNo: "Số tài khoản",
    quantityBondLockdown: "Số lượng trái phiếu phong tỏa",
    quantityBondWaitMatch: "Số lượng trái phiếu chưa khớp lệnh",
    quantityBondWait: "Số lượng trái phiếu chờ về",
    valueMarket: "Giá trị thị trường",
    priceMarket: "Giá thị trường",
    costValue: "Giá trị vốn",
    costPrice: "Giá vốn",
    statusCompleteFile: "Trạng thái hoàn thiện hồ sơ",
    profitCouponReceived: "Tổng lãi coupon đã nhận",
    cashPaybackToExpire: "Số tiền thực nhận nếu nắm giữ đến ngày đáo hạn",
    dividendToExpire: "Số tiền lãi nắm giữ đến ngày đáo hạn",
    dividendExpected: "Số tiền lãi dự kiến đến ngày hiện tại",
    interestRateEarn: "Lãi suất thực nhận",
    quantityBondAvailable: "Số lượng trái phiếu khả dụng",
    perform: "Thực hiện",
    signContract: "Ký hợp đồng",
    cancelOrder: "Hủy lệnh",
    orderConfirm: "Xác nhận lệnh",
    confirmOrder: "Xác nhận giao dịch",
    miss_acc_number: "Qúy khách chưa nhập tài khoản khách hàng",
    miss_value: "Quý khách chưa nhập số tiền",
    total_cost: "Tổng chi phí",
    register_btn: "Đăng ký",
    search_acc: "Tìm kiếm nhanh",
    register_probond: "Đăng ký giao dịch ProBond",
    value_probond: "Số tiền thực hiện",
    temporary_fee_probond: "Phí tạm thu",
    fee_probond: "Phí thực tế",
    day_return_fee: "Số tiền nhận lại cuối ngày",
    required_amount: "Số tiền cần có",
    received_amount: "Số tiền nhận được",
    settled_date: "Chứng khoán/Tiền về",
    registration_confirm: "Xác nhận thông tin đăng ký ProBond",
    bond_information: "Thông tin trái phiếu",
    skip: "Bỏ qua",
    order_buy: "Lệnh mua",
    order_sell: "Lệnh bán",
    promotion_by_bond_code: "Ưu đãi theo mã",
    promotion_by_nav: "Ưu đãi theo NAV",
    total_promotion: "Tổng ưu đãi",
    price_before_promotion: "Giá trước ưu đãi",
    view_contracts: "Xem hợp đồng giao dịch",
    agree_contracts:
      "Tôi đã đọc và đồng ý với toàn bộ các hợp đồng và văn bản ở trên",
    enter_OTP1:
      "Để xác nhận việc giao kết, Khách hàng vui lòng nhập mã OTP từ ứng dụng VNDIRECT hoặc ",
    enter_OTP2: "bấm vào đây",
    enter_OTP3: " để nhận OTP qua SMS",
    confirm_OTP: "Xác nhận OTP",
    confirm: "Xác nhận",
    cancel_contracts: "Hủy hợp đồng",
    reject_contracts: "Từ chối",
    page: "Trang",
    previous: "Trước",
    next: "Sau",
    OTP_has_been_sent: "Mã OTP đã được gửi đến số điện thoại của Quý khách",
    report_cannot_find_sms: "Báo lỗi không nhận được tin nhắn",
    contracts_not_found: "Không tìm thấy hợp đồng",
    report_success: "Thông báo lỗi thành công. Cảm ơn Quý khách!",

    read_all_contracts:
      "Bạn phải xem hết các hợp đồng bên trên trước khi xác nhận.",
    agree_all_contracts: "Bạn phải đồng ý với các hợp đồng ở trên.",
    enter_otp: "Bạn phải nhập OTP để xác nhận.",

    select_careby: "Chọn nhân viên chăm sóc",
    no_careby: "Không chọn nhân viên chăm sóc",
    enter_careby: "Nhập mã nhân viên chăm sóc khác",
    require_careby: "Vui lòng điền nhân viên chăm sóc",
    remain_limit: "Số trái phiếu còn lại",
    noteSellFix:
      "Lệnh bán DBond FIX trên bảng giá chỉ có thể thực hiện vào ngày tất toán đúng trên hợp đồng. Quý khách có nhu cầu tất toán trước hạn hoặc tất toán muộn vui lòng liên hệ nhân viên chăm sóc hoặc tổng đài để được hỗ trợ.",
    DBond: "DBond",
    VBond: "VBond",
    distributionChannel: "Tổ chức phân phối",
    bondCode: "Mã trái phiếu",
    productType: "Loại sản phẩm",
    term: "Kỳ hạn",
    rate: "Lãi suất",
    rateCommitment: "Lãi suất cam kết",
    limitAmount: "Hạn mức còn lại",
    actions: "Thao tác",
    to: "đến",
    from: "từ",
    detail: "Chi tiết",
    buy: "Mua",
    billion: "tỷ",
    copyRight: "Bản quyền thuộc về",
    maximum: "Tối đa",
    month: "tháng",
    year: "năm",
    day: "ngày",
    months: "tháng",
    week: "tuần",
    weeks: "tuần",
    years: "năm",
    days: "ngày",
    remainingTerm: "Kỳ hạn còn lại",
    yieldMaturity: "Lợi suất đến đáo hạn (trước thuế phí)",
    dailySpread: "Chênh lệch mua bán trong ngày",
    difBidAskTooltip: "(Giá VND chào bán - Giá VND chào mua)/Mệnh giá",
    minBalance: "Khối lượng sở hữu tối thiểu",
    maxBalance: "Khối lượng sở hữu tối đa",
    buyPrice: "Giá VNDIRECT chào mua",
    sellPrice: "Giá VNDIRECT chào bán",
    sell: "Bán",
    dataNotFound: "Không có dữ liệu",
    TradingInformation: "Thông tin giao dịch",
    CustomerAccountNo: "Tài khoản khách hàng",
    CustomerFullName: "Tên khách hàng",
    CarebyCode: "Mã NV chăm sóc",
    CarebyFullName: "Tên NV chăm sóc",
    refer: "Mã người giới thiệu",
    referFullName: "Tên người giới thiệu",
    BrokerAccountNo: "Tài khoản VNDIRECT",
    Side: "Lệnh Mua/ Bán",
    Price: "Giá",
    Quantity: "Khối lượng",
    BuyQuantity: "Khối lượng mua",
    RemainQuantity: "Khối lượng còn lại",
    ValueDate: "Ngày thanh toán",
    buyDate: "Ngày mua",
    sellDate: "Ngày bán",
    settlementDate: "Ngày hạch toán",
    Volume: "Tổng giá trị",
    ParValue: "Mệnh giá",
    Issuer: "Tổ chức phát hành",
    TradeDate: "Ngày giao dịch",
    Tax: "Thuế",
    CouponRate: "Tỷ lệ Coupon",
    MaturityDate: "Ngày đáo hạn",
    dateReturnOrder: "Ngày đặt lệnh trả lại",
    provisional: "Tạm tính",
    Yield: "Lợi suất",
    BuyFee: "Phí mua",
    Rate: "Lãi suất",
    TradingPayment: "Thanh toán giao dịch",
    BondPayment: "Thanh toán gốc/ lãi",
    Back: "Quay lại",
    Confirm: "Xác nhận",
    BenefitBankName: "Tên ngân hàng thụ hưởng",
    BranchName: "Tên chi nhánh",
    BenefitAccount: "Tài khoản thụ hưởng",
    BenefitAccountName: "Tên chủ tài khoản thụ hưởng",
    PaymentByVNDAccount: "Thanh toán bằng tài khoản tại VNDIRECT",
    SellFee: "Phí bán",
    DealConfirm: "Tôi đồng ý đề nghị thực hiện giao dịch",
    agree: "Đồng ý",
    DBondDetail:
      "Trái phiếu D-bond là sản phẩm phân phối Trái phiếu kèm theo điều khoản mua lại. Chi tiết xem tại đây",
    VBondDetail:
      "Trái phiếu D-bond là sản phẩm phân phối Trái phiếu kèm theo điều khoản mua lại. Chi tiết xem tại đây",
    CustodyCenter: "Tổ chức lưu ký",
    CollateralAsset: "Tài sản đảm bảo",
    IssueDate: "Ngày phát hành",
    RateType: "Loại lãi suất",
    Fix: "Cố định",
    Float: "Thả nổi",
    BondPaidIntPeriodYear: "Kỳ trả lãi",
    BondCodeNotFound: "Không tìm được mã trái phiếu này.",
    timesPerYear: "lần/năm",

    "Mã trái phiếu": "Mã trái phiếu",
    Bán: "Bán",
    "Chi tiết": "Chi tiết",
    "Không có dữ liệu": "Không có dữ liệu",
    "Lọc danh mục theo mã": "Lọc danh mục theo mã",
    "Danh mục trái phiếu": "Danh mục trái phiếu",
    "Quyền trả lại": "Quyền trả lại",
    "Deal id": "Mã hợp đồng",
    "Ngày mua": "Ngày mua",
    "Loại kỳ hạn": "Loại kỳ hạn",
    "Ngày trả lại cuối cùng": "Ngày trả lại",
    "Lãi suất": "Lãi suất",
    "Số lượng": "Số lượng",
    "Giá mua": "Giá mua",
    "Tổng giá trị mua": "Tổng giá trị mua",
    "Thao tác": "Thao tác",
    "Ngày đáo hạn": "Ngày đáo hạn",
    "Mệnh giá": "Mệnh giá",
    totalAmount: "Tổng giá trị",
    bondQuantity: "Số lượng trái phiếu",
    fromDate: "Từ ngày",
    toDate: "Đến ngày",
    advancedSearch: "Tìm kiếm nâng cao",
    pleaseSelectBondCode: "Chọn mã trái phiếu",
    vndirectAccount: "Tài khoản VNDIRECT",
    bankAccount: "Tài khoản Ngân hàng",
    pleaseSelectBank: "Xin chọn tài khoản Ngân hàng",
    inputRequired: "Xin vui lòng nhập đầy đủ thông tin",
    acceptTermRequired: "Xin vui lòng đồng ý thực hiện giao dịch",

    Lệnh: "Lệnh",
    Mua: "Mua",
    "Trạng thái": "Trạng thái",
    PENDING: "Chờ duyệt lệnh",
    APPROVED: "Chờ xác nhận",
    CONFIRMED: "Chờ khớp lệnh",
    MATCHED: "Chờ hạch toán",
    SETTLED: "Chờ hoàn thiện hồ sơ",
    COMPLETED_LEG1: "Hoàn tất",
    COMPLETED: "Hoàn tất",
    CANCELED: "Hủy thành công",
    REJECTED: "Từ chối",
    "Không có lệnh": "Không có lệnh",
    "Mã giao dịch": "Mã giao dịch",
    Ngày: "Ngày",
    "Loại lệnh": "Loại lệnh",
    "Loại sản phẩm": "Loại sản phẩm",
    "Kỳ hạn gốc": "Kỳ hạn gốc",
    "Giá thực hiện": "Giá thực hiện",
    "Tổng giá trị": "Tổng giá trị",
    "Trạng thái lệnh": "Trạng thái lệnh",

    wantToCancel: "Quý khách muốn hủy lệnh này?",
    removeSuccess: "Hủy lệnh thành công",
    placeOrderSuccess: "Đặt lệnh thành công.",
    confirmProbondSuccess: "Xác nhận giao dịch thành công",
    rejectProbondSuccess: "Từ chối giao dịch thành công",
    orderbook: "Sổ lệnh",

    yieldTooltip:
      "Lãi suất trước thuế, phí nhận được khi mua trái phiếu ngày hôm nay và nắm giữ đến đáo hạn",
    minBalanceTooltip:
      "Số trái phiếu tối thiểu cần duy trì sau mỗi lệnh mua/bán để tiếp tục là nhà đầu tư của mã trái phiếu tương ứng",
    sellPriceTooltip:
      "Giá khách hàng có thể mua trái phiếu ngày hôm nay trước khi áp dụng ưu đãi",
    buyPriceTooltip: "Giá khách hàng có thể bán lại trái phiếu ngày hôm nay",

    dBondRateNote:
      "Lãi suất thực nhận sau thuế phí, chưa áp dụng các chương trình khuyến mãi của VNDIRECT",
    vBondRateNote:
      "Mức lãi suất trước thuế thu nhập cá nhân (nếu có) nếu nắm giữ đến ngày đáo hạn với mức giá tương ứng giá chào bán",
    vBondRemainTerm:
      "Kỳ hạn còn lại: Kỳ hạn tính bằng năm tính đến ngày đáo hạn của Trái phiếu",
    congratsPro: "Chúc mừng Quý khách đã là Nhà đầu tư chuyên nghiệp!",
    note65:
      "VNDIRECT tạm dừng giao dịch MUA trái phiếu online tại bảng giá web để điều chỉnh quy trình phù hợp với Nghị định số 65/2022/NĐ-CP. Thời gian hoàn tất dự kiến: 24h ngày 29/09/2022. Quý khách vui lòng liên hệ nhân viên chăm sóc tài khoản hoặc tổng đài 1900545409 để được hỗ trợ.",
    businessCustomerNote:
      "Quý khách nhà đầu tư tổ chức vui lòng liên hệ Tổng đài 1900545409 hoặc NVCS để được tư vấn nếu có nhu cầu MUA trái phiếu.",
    dBondGuideLine: "Quý khách có thể tìm hiểu thông tin chi tiết về DBond",
    dBondMassGuideLine:
      "D-BOND Mass gồm các mã trái phiếu DBond dành cho tất cả nhà đầu tư. Quý khách có thể tìm hiểu thêm về DBond",
    dBondProGuideLine:
      "D-BOND Pro gồm các mã trái phiếu DBond dành riêng cho nhà đầu tư chuyên nghiệp. Tìm hiểu thêm",

    vBondGuideLine: "Quý khách có thể tìm hiểu thông tin chi tiết về VBond",
    vBondMassGuideLine:
      "V-BOND Mass gồm các mã trái phiếu VBond dành cho tất cả nhà đầu tư. Quý khách có thể tìm hiểu thêm về VBond",
    vBondProGuideLine:
      "V-BOND Pro gồm các mã trái phiếu VBond dành riêng cho nhà đầu tư chuyên nghiệp. Tìm hiểu thêm",
    normalInvestor:
      "Quý khách chưa phải Nhà đầu tư chuyên nghiệp (NĐTCN) tại VNDIRECT. Vui lòng liên hệ Nhân viên chăm sóc hoặc gọi tổng đài 1900 54 54 09 để được hỗ trợ.",
    proInvestorInfo: "Nhà đầu tư chuyên nghiệp là gì? Vui lòng xem",
    proInvestorHelp:
      "Quý khách chưa phải Nhà đầu tư chuyên nghiệp tại VNDIRECT. Chúng tôi có thể hỗ trợ Quý khách",
    here: "TẠI ĐÂY",
    productInfo: "GIỚI THIỆU SẢN PHẨM",
    bondList: "DANH SÁCH TRÁI PHIẾU",
    vbondInfo:
      "là sản phẩm đầu tư trái phiếu tại VNDIRECT gồm trái phiếu 100% có tài sản đảm bảo, được chọn lọc kỹ càng theo các tiêu chí về quy mô, chất lượng tài sản, ngành nghề lợi thế theo chu kỳ kinh tế. Khách hàng có nhu cầu tìm hiểu chi tiết hơn về sản phẩm trái phiếu VBond vui lòng xem chi tiết",
    ngayTraLaiTooltip:
      "Đối với sản phẩm VAR, giá trị tương ứng với ngày trả lại chậm nhất",
    full: "Hết hàng",
    available: "Còn hàng",
    fullMessage:
      "Hiện sản phẩm này đang hết hàng. Quý khách vui lòng liên hệ Nhân viên chăm sóc tài khoản hoặc Tổng đài 1900545409 để biết thêm thông tin chi tiết",
    tooltipMaMoiGioi:
      "Quý khách vui lòng điền Mã Nhân viên chăm sóc tài khoản để VNDIRECT có thể phục vụ Quý khách tốt hơn.",
    ngayHieuLuc: "Ngày hiệu lực",
    bond_certificate: "Nhận trích lục sổ đăng ký NSHTP/GCNSHTP (nếu có)",
    bond_certificate_comfirm: "Nhận trích lục sổ đăng ký NSHTP/GCNSHTP",
    bond_certificate_tooltip:
      "Quý khách lựa chọn Không để đồng ý gửi Giấy Trích lục sổ đăng ký NSHTP/GCNSHTP tại VNDIRECT và tiết kiệm thời gian khi thực hiện bán lại.",
    yes: "Có",
    no: "Không",
    fix_tooltip:
      "Là sản phẩm mua bán Trái phiếu mà Khách hàng có Quyền trả lại cho VNDIRECT sau kỳ hạn nắm giữ cố định và hưởng mức lãi tức xác định từ trước",
    var_tooltip:
      "Là sản phẩm mua bán Trái phiếu mà Khách hàng có Quyền trả lại cho VNDIRECT trong suốt kỳ hạn nắm giữ và hưởng mức lãi tức tăng dần theo thời hạn nắm giữ",
    bondType: "Sản phẩm",
    requiredBankDetail:
      "Quý khách chưa đăng ký tài khoản ngân hàng để nhận gốc lãi. <br />Vui lòng liên hệ 1900545409 để đăng ký tài khoản ngân hàng với VNDIRECT.",
    requiredMinQuantity: "Quý khách vui lòng nhập khối lượng tối thiểu",
    requiredMaxQuantity: "Quý khách vui lòng nhập khối lượng tối đa",
    requiredAccountNo: "Quý khách vui lòng chọn tài khoản giao dịch",
    minQuantity: "Khối lượng mua tối thiểu",
    promotion: "Ưu đãi",
    real_rate: "Lãi suất thực nhận",
    currentPrice: "Giá hiện tại",
    currentAmount: "Giá trị hiện tại",
    sellableQuantity: "Khối lượng có thể bán",
    codePromotion: "Mã ưu đãi",
    version: "Bản quyền thuộc về VNDIRECT v",
    forProInvestor: "Áp dụng điều kiện NĐTCN",
    couponFrequency: "Tần suất trả coupon",
    bondUnit: "trái phiếu",
    brochure: "Thông tin chi tiết",
    bondCodeShort: "Trái phiếu",
    bondIssuanceDocuments: "Tài liệu phát hành Trái phiếu",
    bondIssuanceDocument1:
      "Tôi đã xem toàn bộ hồ sơ liên quan đến đợt phát hành trái phiếu ",
    bondIssuanceDocument2: " và đồng ý đề nghị thực hiện giao dịch.",
    pending: "Đang cập nhật",
    advancedFilter: "Bộ lọc nâng cao",
    today: "Hôm nay",
    yesterday: "Hôm qua",
    shortName: "Tên rút gọn",
    originalBond: "Mã trái phiếu gốc",
    selectIssuer: "Chọn tổ chức phát hành",
    selectTerm: "Chọn kỳ hạn",
    profileIncomplete: "Chưa hoàn thiện hồ sơ",
    couponReceived: "Đã nhận coupon",
    completeProfile: "Hoàn thiện hồ sơ",
    totalValue: "Giá trị mua",
    totalCurrentValue: "Tổng giá trị hiện tại",
    complete: "Đã hoàn thiện",
    incomplete: "Chưa hoàn thiện",
    currency: "đồng",
    rateBeforePromotion: "Lãi suất trước ưu đãi",
    totalPayment: "Tổng thanh toán",
    fee: "Phí",
    temporaryFee: "Phí tạm thu",
    tipTempoaryFee1:
      "Để hệ thống ghi nhận giao dịch, VNDIRECT tạm thu mức phí ",
    tipTempoaryFee2:
      "giá trị giao dịch và lớn hơn phí giao dịch thực tế theo biểu phí của HNX là 0.0054%. VNDIRECT hoàn trả phần tiền chênh lệnh của phí tạm thu trừ đi phí giao dịch thực tế vào cuối ngày giao dịch; hoàn lại phí giao dịch thực tế vào ngày thanh toán gốc lãi trái phiếu.",
    leg2TradeDate: "Ngày trả lại",
    dBondChannel:
      "là kênh đầu tư trái phiếu doanh nghiệp để hưởng lãi suất hấp dẫn với các lựa chọn về thời gian đầu tư linh hoạt (từ mindate – maxdate ngày). Trái phiếu thuộc danh mục DBond được chuyên gia VNDIRECT đánh giá và lựa chọn từ các doanh nghiệp hàng đầu, có sự phát triển bền vững trong các lĩnh vực nền tảng như năng lượng, hạ tầng, tiện ích, dịch vụ, bất động sản… Đặc biệt, VNDIRECT cung cấp thêm cam kết mua lại áp dụng theo thời gian đầu tư để đảm bảo an toàn tối đa cho Nhà đầu tư.",
    dBondChannel1:
      "là kênh đầu tư trái phiếu để hưởng lãi suất hấp dẫn với đa dạng các lựa chọn về thời gian đầu tư cố định (từ ",
    dBondChannel2:
      "ngày). Trái phiếu thuộc danh mục DBond được chuyên gia VNDIRECT đánh giá và lựa chọn từ các tổ chức phát hành là định chế tài chính, doanh nghiệp đầu ngành trên nhiều lĩnh vực. Đặc biệt, VNDIRECT cung cấp thêm cam kết mua lại tại ngày xác định (ngày Trả lại quy định trong Hợp đồng mua) để đảm bảo an toàn tối đa cho Nhà đầu tư.",
    dBondLearnMore:
      "Khách hàng có nhu cầu tìm hiểu chi tiết hơn về sản phẩm trái phiếu DBond vui lòng xem ",
    dBondCorpRatebyTerm: "Lãi suất DBond Corp theo các kỳ hạn",
    dBondFiRatebyTerm: "Lãi suất DBond FI theo các kỳ hạn",
    promotionByNav: "Ưu đãi cộng thêm vào lãi suất DBond theo NAV trái phiếu",
    bondNavTooltip:
      "NAV trái phiếu được tính bằng tổng giá trị mệnh giá DBond, VBond khách hàng đang sở hữu và giá trị mệnh giá DBond khách hàng có nhu cầu mua",
    levelNav: "Mức NAV",
    bondForProInvest: "Trái phiếu dành riêng cho Nhà đầu tư chuyên nghiệp.",
    investmentAmount: "Số tiền đầu tư",
    inputMoney: "Nhập số tiền muốn đầu tư",
    minimumTerm: "Kỳ hạn tối thiểu",
    anyTerm: "Tất cả kỳ hạn",
    anyIssuer: "Tất cả TCPH",
    productBondType: "Loại trái phiếu",
    filter: "Lọc",
    forAllInvestor: "Dành cho tất cả nhà đầu tư",
    allBonds: "Tất cả trái phiếu",
    selectYield: "Chọn mức lợi suất",
    couponFixed: "Cố định ",
    seeMore: "Xem thêm",
    seeLess: "Thu gọn",
    buyRate: "Lãi suất mua",
    note: "Lưu ý",
    noteExpire1:
      "Quý khách đang lựa chọn tất toán trước hạn, tương ứng lãi suất được hưởng là lãi suất không kỳ hạn.",
    noteExpire2: "Quý khách có chắc chắn muốn tất toán trước hạn?",
    titleContract: "Giao kết hợp đồng",
    contractOpen:
      "Khách hàng đọc, hiểu và thực hiện giao kết các hợp đồng và văn bản/chứng từ sau đây dưới hình thức giao dịch điện tử.",
    contractCheck:
      "Bằng việc thực hiện xác nhận dưới đây, Khách hàng khẳng định đồng ý với toàn bộ nội dung của tất cả các hợp đồng, văn bản/chứng từ nêu trên và chấp thuận việc giao kết hợp đồng và văn bản/chứng từ giao dịch với VNDIRECT.",
    contractComfirm:
      "Để xác nhận việc giao kết, Khách hàng vui lòng nhập mã OTP từ ứng dụng VNDIRECT hoặc bấm vào đây để nhận OTP qua SMS",
    errorAccount:
      "Tài khoản được chọn chưa kích hoạt. Vui lòng chọn tài khoản khác hoặc liên hệ nhân viên chăm sóc",
    errorBankAccount:
      "Trạng thái của tài khoản chưa thể thực hiện giao dịch trái phiếu này",
    finalSettlement: "Quý khách vui lòng lựa chọn phương thức tất toán",
    error1: "Đặt lệnh không thành công.",
    vbondMarket:
      "Nhà đầu tư có thể đăng tải nhu cầu MUA/BÁN trái phiếu VBOND trên VBond Marketplace ",
    vbondTool:
      "Nhà đầu tư tải tool giá để tính toán giá MUA/BÁN phù hợp với nhu cầu ",
    rate_vip: "Lãi suất VIP (%/năm)",
    tooltip_rate_vip:
      "Lãi suất VIP được áp dụng khi tổng giá trị mệnh giá DBond, VBond khách hàng đang sở hữu và giá trị mệnh giá DBond khách hàng có nhu cầu mua từ 10 tỉ trở lên.",
    percentYear: "(%/năm)",
    currentBondValue: "Giá trị hiện tại của trái phiếu",
    tipCurrentBondValue:
      "Đươc định giá theo công thức tài chính dựa trên giá mua, lãi suất trái phiếu và thời gian nắm giữ. Trường hợp KH có nhu cầu bán trái phiếu vui lòng tham khảo thêm giá thị trường ",
    privatePlacementBond: "Trái phiếu doanh nghiệp riêng lẻ",
    publicOfferingBond: "Trái phiếu phát hành ra công chúng",
    transferLimited: "Hạn chế chuyển nhượng",
    tipTransferLimited: "Giao dịch bị hạn chế không thể mua/bán",
    tip_datereturn_order:
      "Đối với trái phiếu niêm yết, Quý khách cần xác nhận lệnh bán trái phiếu trước 14h30 ngày làm việc liền trước Ngày trả lại trên hợp đồng để nhận gốc lãi tại Ngày trả lại.",
    tipCustodyBond:
      "Quý khách vui lòng thực hiện ký gửi trái phiếu để có thể đặt lệnh BÁN. Chi tiết liên hệ NVCS hoặc tổng đài 1900 54 54 09",
  },
  en: {
    poLabelDbond: "DBond portfolio",
    poLabelCustodyDbond: "Undeposited DBond portfolio",
    poLabelVbond: "VBond portfolio",
    poLabelCustodyVbond: "Undeposited VBond portfolio",
    ListedBond: "Listed Bond",
    OtherBond: "Other Bond",
    GovernmentBond: "Government Bond",
    ConvertibleBond: "Convertible Bond",
    otherBond: "Other Bond",
    interestBondCoupon: "Interest rate",
    averageBuyPrice: "Average buying price",
    accountNo: "Account No",
    quantityBondLockdown: "Other blocked quantity",
    quantityBondWaitMatch: "Unfill sell quantity",
    quantityBondWait: "Receiving quantity",
    valueMarket: "Market value",
    priceMarket: "Market price",
    costValue: "Cost value",
    costPrice: "Cost price",
    statusCompleteFile: "Contract status",
    profitCouponReceived: "Received coupon payment",
    cashPaybackToExpire: "Total value if holding until expiry date",
    dividendToExpire: "Interest if holding until expiry date",
    dividendExpected: "Accrued interest",
    interestRateEarn: "Interest rate",
    quantityBondAvailable: "Quantity bond available",
    bondQuantity: "Bond quantity",
    perform: "Perform",
    signContract: "Sign contract",
    cancelOrder: "Reject",
    orderConfirm: "Confirm order",
    confirmOrder: "Confirm order",
    miss_acc_number: "Missing account number",
    miss_value: "Missing value",
    total_cost: "Total cost",
    register_btn: "Register",
    search_acc: "Search",
    register_probond: "Register for PROBOND",
    value_probond: "Value",
    temporary_fee_probond: "Temporary fee",
    fee_probond: "Fee",
    day_return_fee: "End of day return fee",
    required_amount: "Required Amount",
    received_amount: "Received Amount",
    settled_date: "Settled Date",
    registration_confirm: "PROBOND registration confirmation",
    bond_information: "Bond information",
    skip: "Skip",
    order_buy: "Order buy",
    order_sell: "Order sell",
    promotion_by_bond_code: "Promotion by bond code",
    promotion_by_nav: "Promotion by NAV",
    total_promotion: "Total promotion",
    price_before_promotion: "Price before promotion",
    view_contracts: "View contracts",
    agree_contracts:
      "I have read and agree with all the above contracts and documents",
    enter_OTP1:
      "To confirm your transactions, please enter the OTP from VNDIRECT app or ",
    enter_OTP2: "click here",
    enter_OTP3: " to get SMS OTP",
    confirm_OTP: "Confirm OTP",
    confirm: "Confirm",
    cancel_contracts: "Cancel",
    reject_contracts: "Reject",
    page: "Page",
    previous: "Previous",
    next: "Next",
    OTP_has_been_sent: "OTP has been sent to your phone",
    report_cannot_find_sms: "Can't find the SMS? Report here",
    contracts_not_found: "Contracts not found",
    report_success: " Reported successfully. Thank you!",

    read_all_contracts:
      "You have to read all the above contracts before confirming.",
    agree_all_contracts: "You have to agree with the above contracts.",
    enter_otp: "You have to enter OTP to confirm.",

    select_careby: "Select Careby",
    no_careby: "No Careby code",
    enter_careby: "Other Careby code",
    require_careby: "Please enter the Careby code",
    agree: "Agree",
    remain_limit: "Available Quantity",
    noteSellFix:
      "Selling a DBond FIX deal online can only take place on leg2 trade date in the contract. If customer wishes to sell before or after leg2 trade date, please contact your careby or call our hotline for support.",
    DBond: "DBond",
    VBond: "VBond",
    distributionChannel: "Distribution Channel",
    bondCode: "Bond Code",
    productType: "Product Type",
    term: "Terms",
    rate: "Rate",
    rateCommitment: "Rate",
    limitAmount: "Limit Amount",
    actions: "Actions",
    to: "to",
    from: "From",
    detail: "Detail",
    buy: "Buy",
    billion: "B",
    copyRight: "Copyright",
    maximum: "Maximum",
    month: "month",
    year: "year",
    day: "day",
    months: "months",
    week: "week",
    weeks: "weeks",
    years: "years",
    days: "days",
    remainingTerm: "Remaining Term",
    yieldMaturity: "Yield to Maturity (before tax and fees)",
    dailySpread: "Daily Spread",
    difBidAskTooltip: "(Ask - Bid)/Par value",
    minBalance: "Minimum Balance",
    maxBalance: "Maximum Balance",
    buyPrice: "Bid",
    sellPrice: "Ask",
    sell: "Sell",
    dataNotFound: "Data not found",
    TradingInformation: "Trading Information",
    CustomerAccountNo: "Customer Account No",
    CustomerFullName: "Customer Full Name",
    CarebyCode: "Careby Code",
    CarebyFullName: "Careby Full Name",
    refer: "Reference Code",
    referFullName: "Referrer Full Name",
    BrokerAccountNo: "Broker Account No",
    Side: "Side",
    Price: "Price",
    Quantity: "Quantity",
    BuyQuantity: "Quantity",
    RemainQuantity: "Remain Quantity",
    ValueDate: "Value Date",
    buyDate: "Buy Date",
    sellDate: "Sell Date",
    settlementDate: "Settlement Date",
    Volume: "Volume",
    ParValue: "Par value",
    Issuer: "Issuer",
    TradeDate: "Trade Date",
    Tax: "Tax",
    CouponRate: "Coupon Rate (Bond)",
    MaturityDate: "Maturity Date",
    provisional: "Provisional",
    Yield: "Yield",
    BuyFee: "Buy Fee",
    Rate: "Rate",
    TradingPayment: "Trading payment",
    BondPayment: "Bond payment",
    Back: "Go back",
    Confirm: "Confirm",
    BenefitBankName: "Benefit Bank Name",
    BranchName: "Branch Name",
    BenefitAccount: "Benefit Account",
    BenefitAccountName: "Benefit Account Name",
    PaymentByVNDAccount: "Payment by VNDIRECT account",
    SellFee: "Sell Fee",
    DealConfirm: "I agree to confirm this deal",

    DBondDetail:
      "DBond product is bond product that will be repurchased in leg2 trade date. See more detail",
    VBondDetail:
      "VBond product is bond product that will be not repurchased in leg2 trade date. See more detail",
    CustodyCenter: "Custody Center",
    CollateralAsset: "Collateral Asset",
    IssueDate: "Issue Date",
    RateType: "Rate Type",
    Fix: "Fix",
    Float: "Float",
    BondPaidIntPeriodYear: "Number of coupon payments",
    BondCodeNotFound: "Bond code is not exist.",
    timesPerYear: "times/year",

    "Mã trái phiếu": "Bond code",
    Bán: "Sell",
    "Chi tiết": "Detail",
    "Không có dữ liệu": "Data not found",
    "Lọc danh mục theo mã": "Search by symbol",
    "Danh mục trái phiếu": "Bond Portfolio",
    "Quyền trả lại": "Leg2 Return",
    "Deal id": "Deal id",
    "Ngày mua": "Buy Date",
    "Loại kỳ hạn": "Product type",
    "Ngày trả lại cuối cùng": "Leg2 Trade Date",
    "Lãi suất": "Rate",
    "Số lượng": "Quantity",
    "Giá mua": "Buy Price",
    "Tổng giá trị mua": "Total Buy Value",
    "Thao tác": "Actions",
    "Ngày đáo hạn": "Maturity Date",
    "Mệnh giá": "Par Value",
    totalAmount: "Total Amount",

    fromDate: "From date",
    toDate: "To date",
    advancedSearch: "Advanced search",
    pleaseSelectBondCode: "Please select bond code",
    vndirectAccount: "VNDIRECT account",
    bankAccount: "Bank account",
    pleaseSelectBank: "Please select bank account",
    inputRequired: "Please enter required informations",
    acceptTermRequired: "You must agree to make the transaction",

    Lệnh: "SIDE",
    Mua: "Buy",
    "Trạng thái": "Status",
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    CONFIRMED: "CONFIRMED",
    MATCHED: "MATCHED",
    SETTLED: "SETTLED",
    COMPLETED_LEG1: "COMPLETED",
    COMPLETED: "COMPLETED",
    CANCELED: "CANCELED",
    REJECTED: "REJECTED",
    "Không có lệnh": "Currently there's no order",
    "Mã giao dịch": "Deal/ Transaction ID",
    Ngày: "Date",
    "Loại lệnh": "Side",
    "Loại sản phẩm": "Product Type",
    "Kỳ hạn gốc": "Term",
    "Giá thực hiện": "Price",
    "Tổng giá trị": "Total Amount",
    "Trạng thái lệnh": "Status",

    wantToCancel: "Do you want to cancel this order?",
    removeSuccess: "Successfully cancel order",
    placeOrderSuccess: "Place Order success.",
    confirmProbondSuccess: "Successfully transaction confirmation",
    rejectProbondSuccess: "Successfully transaction rejection",
    orderbook: "Order book",

    yieldTooltip:
      "The yield before taxes and fees when buying bonds today and holding until maturity",
    minBalanceTooltip:
      "The minimum amount of bonds required to maintain after each buy/sell transaction to keep 'bondholder' status",
    sellPriceTooltip:
      "The price before any promotion that customers can buy the bond at today",
    buyPriceTooltip: "The price that customers can sell the bond at today",

    dBondRateNote:
      "Real interest rate after fees and taxes, excluding with promotions from VNDIRECT",
    vBondRateNote:
      "The interest rate before personal income tax in case the bond is held to the maturity date at the ask price",
    vBondRemainTerm: "Remaining term: counted by years to the maturity date",
    congratsPro: "Congrats! You are a Professional Investor.",
    note65:
      "VNDIRECT is adjusting the process of bond trading according to Decree 65/2022/ND-CP, so please contact Hotline 1900545409 or Careby for advice if you need to BUY bonds.",
    dBondGuideLine: "Details of DBond is available",
    dBondMassGuideLine:
      "D-BOND Mass lists all DBonds for every investor. For more information about DBond, visit",
    dBondProGuideLine:
      "D-BOND Pro lists DBonds dedicated for professional investor. For more information, visit ",
    vBondGuideLine: "Details of VBond is available",
    vBondMassGuideLine:
      "V-BOND Mass lists all VBonds for every investor. For more information about VBond, visit",
    vBondProGuideLine:
      "V-BOND Pro lists VBonds dedicated for professional investor. For more information, visit ",
    normalInvestor:
      "You are not yet a Professional Investor at VNDIRECT. Please contact Hotline 1900 54 54 09 or Careby for further support.",

    proInvestorInfo: "What is a Professional Investor? Visit ",
    proInvestorHelp:
      "You are not yet a Professional Investor at VNDIRECT. We can assist you",
    here: "HERE",
    productInfo: "PRODUCT INTRODUCTION",
    bondList: "BOND LIST",
    vbondInfo:
      "is an investment product at VNDIRECT consisting of 100% bonds with collateral, are carefully selected based on size, asset quality, advantageous industries according to the economic cycle. To learn more about VBond products, please see ",
    ngayTraLaiTooltip: "For VAR deals, the date is the Final leg2 trade date",
    full: "Full",
    available: "Available",
    fullMessage:
      "This product is sold out. Please contact to VNDIRECT customercare staff or 1900545409 for further information",
    tooltipMaMoiGioi: "Please insert the Staff code for further services.",
    ngayHieuLuc: "Value date",
    bond_certificate: "Bond certificate (if any)",
    bond_certificate_comfirm: "Bond certificate",
    bond_certificate_tooltip:
      "Please tick into No for releasing bond certificate at VNDIRECT and saving time when making sale transaction.",
    yes: "Yes",
    no: "No",
    fix_tooltip:
      "Bond deal product that the customers have right to refund to VNDIRECT after fixed term with a definite interest rate",
    var_tooltip:
      "Bond deal product that the customers have right to refund to VNDIRECT during the term with ascending interest rate",
    bondType: "Bond Type",
    requiredBankDetail:
      "Bank account has not been registered yet. <br />Please contact 1900545409 for further registration.",
    requiredMinQuantity: "Please input the quantity greater",
    requiredMaxQuantity: "Please input the quantity lesser",
    requiredAccountNo: "Please select the account number",
    minQuantity: "Minimum quantity",
    promotion: "Promotion",
    real_rate: "Real Interest Rate",
    currentPrice: "Current price",
    currentAmount: "Current amount",
    sellableQuantity: "Sellable quantity",
    codePromotion: "Code promotion",
    version: "Copyright VNDIRECT. All rights reserved. v",
    couponFrequency: "Coupon Frequency",
    bondUnit: "bonds",
    brochure: "Detail information",
    bondCodeShort: "Bond Info",
    bondIssuanceDocuments: "Bond Issuance Documents",
    bondIssuanceDocument1:
      "I have read all documents related to the issue of this bond ",
    bondIssuanceDocument2: " and agree to confirm this deal.",
    pending: "Pending",
    advancedFilter: "Advanced Filter",
    today: "Today",
    yesterday: "Yesterday",
    shortName: "Short Name",
    originalBond: "Original bond code",
    selectIssuer: "Select Issuer",
    selectTerm: "Select Term",
    profileIncomplete: "Profile Incomplete",
    couponReceived: "Coupon Received",
    completeProfile: "Complete Profile",
    totalValue: "Total Value",
    totalCurrentValue: "Total Current Value",
    complete: "Complete",
    incomplete: "Incomplete",
    currency: "dong",
    rateBeforePromotion: "Rate Before Promotion",
    totalPayment: "Total Payment",
    fee: "Fee",
    temporaryFee: "Temporary hold",
    tipTempoaryFee1:
      "A fee amount will be temporarily hold in your total trading amount as a way to guarantee your order. The temporary hold is equivalent to ",
    tipTempoaryFee2:
      "x Trading value, which is higher than the actual transaction fee according to HNX's fee schedule (of 0.0054%). We will unhold the difference at the end of the trading day and return the actual transaction fee at the Return date.",
    leg2TradeDate: "Leg2 Trade Date",
    dateReturnOrder: "Leg2 Trade Date",
    dBondChannel:
      " is a channel to invest in corporate bonds to enjoy attractive interest rates with flexible investment terms (from {mindate} to {maxdate} days). Bonds in the DBond portfolio are evaluated and selected by VNDIRECT experts from leading businesses with sustainable development in fundamental fields such as real estate, utilities, infrastructure, services... Especially, VNDIRECT provides repurchase commitments according to the investment terrms to ensure maximum safety for Investors.",
    dBondChannel1:
      " is a channel to invest in bonds to enjoy attractive interest rates with various choices of fixed investment terms (from ",
    dBondChannel2:
      " days). Bonds in the DBond portfolio are evaluated and selected by VNDIRECT experts from leading businesses with sustainable development in fundamental fields such as real estate, utilities, infrastructure, services... Especially, VNDIRECT provides repurchase commitments at a fixed date (the Return date stated in the Buy contract) to ensure maximum safety for Investors.",
    dBondLearnMore: "To learn more about DBond products, please see",
    dBondCorpRatebyTerm: "DBond Corp interest rate by terms",
    dBondFiRatebyTerm: "DBond FI interest rate by terms",
    promotionByNav: "Promotion by NAV",
    bondNavTooltip:
      "Bond NAV is the sum of the par value of DBond, VBond customer owns and the par value of DBond that customer wishes to buy",
    levelNav: "NAV",
    bondForProInvest: "Exclusive product for Professional Investors.",
    investmentAmount: "Investment Amount",
    inputMoney: "Input money amount",
    minimumTerm: "Minimum term",
    anyTerm: "Any terms",
    anyIssuer: "Any Issuers",
    productBondType: "Product Type",
    filter: "Filter",
    forAllInvestor: "For all Investors",
    forProInvestor: "Professional investor status required",
    allBonds: "All Bonds",
    selectYield: "Select Yield",
    couponFixed: "Fixed ",
    seeMore: "See more",
    seeLess: "See less",
    buyRate: "Interest Rate",
    note: "Note",
    noteExpire1:
      "You are settling this bond before the Leg 2 Settled Date, the corresponding interest rate will be the non-term rate.",
    noteExpire2: "Are you sure to proceed?",
    titleContract: "SIGN THE CONTRACT",
    contractOpen:
      "Kindly read, understand and sign the following contracts and documents in the form of electronic transactions.",
    contractCheck:
      "By accepting, the Customer confirms to agree with the entire content of all the above contracts and documents and accepts the signing of the contract and transaction documents with VNDIRECT.",
    contractComfirm:
      "To confirm your transactions, please enter the OTP from VNDIRECT app or click here to receive OTP via SMS",
    errorAccount: "The account is not activated",
    errorBankAccount:
      "The account status is not allowed to place order for this bond",
    finalSettlement: "Please select settlement method",
    businessCustomerNote:
      "Business investors, please contact 1900545409 or Careby for advice if you need to BUY bonds.",
    error1: "Create deal failed.",
    vbondMarket:
      "Investors can post their needs to BUY/SELL VBOND on the Stockbook corporate bond forum ",
    vbondTool:
      "Investors can download excel tool to input expected BUY/SELL price ",
    rate_vip: "Rate VIP (%/year)",
    tooltip_rate_vip:
      "Lãi suất VIP được áp dụng khi tổng giá trị mệnh giá DBond, VBond khách hàng đang sở hữu và giá trị mệnh giá DBond khách hàng có nhu cầu mua từ 10 tỉ trở lên.",
    percentYear: "(%/year)",
    currentBondValue: "Bond present value",
    tipCurrentBondValue:
      "Is calculated by using a financial formula that factors the purchase price, the coupon rate of the bond and the holding period. In case customers wish to sell bonds, please refer to the market price ",
    privatePlacementBond: "Private Placement Bond",
    publicOfferingBond: "Public Offering Bond",
    transferLimited: "Transfer limited",
    tipTransferLimited: "Transaction is limited impossible buy/sell",
    tip_datereturn_order: "",
    tipCustodyBond:
      "Please complete the deposit procedures for the bond to be able to place a SELL order. For details, contact Careby or hotline 1900 54 54 09",
  },
};

export default BondLabelMap;
